name: 'YAML file validation against JSON Schema'
description: 'Validates YAML file schema against provided JSON Schema file'
inputs:
  json-schema-file:
    description: 'JSON Schema file to validate against'
    required: true
  yaml-file-dir:
    description: 'Comma separated list of YAML files and/or directories that require validation'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.json-schema-file }}
    - ${{ inputs.yaml-file-dir }}
