name: 'YAML Schema validator'
description: 'Validates YAML file schema against provided JSON Schema file'
inputs:
  yaml-file:
    description: 'YAML file that requires validation'
    required: true
  json-file:
    description: 'JSON Schema file to validate against'
outputs:
  result:
    description: 'Result of validation'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.yaml-file }}
    - ${{ inputs.json-file }}
