name: Self Test

on:
  pull_request:
    branches: [ main ]

jobs:
  runValidation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if directory is not scanned, due to recursive is False (should PASS)
        id: validation
        uses: lyubick/action-YAML-schema-validator@test
        with:
          json-schema-file: test/json_schema.json
          yaml-file-dir: test/
      - name: Check if directory is scanned, due to recursive is True (should FAIL)
        id: invalidation
        continue-on-error: true
        uses: lyubick/action-YAML-schema-validator@test
        with:
          json-schema-file: test/json_schema.json
          yaml-file-dir: test/
          recursive: true
