name: Self Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runValidation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check 2 YAML files against JSON Schema
        id: validation
        uses: lyubick/action-YAML-schema-validator@test
        with:
          yaml-file: test/yaml_valid.yaml
          json-file: test/json_schema.json
      - name: Check 2 YAML files against JSON Schema
        id: invalidation
        continue-on-error: true
        uses: lyubick/action-YAML-schema-validator@test
        with:
          yaml-file: test/yaml_invalid.yaml
          json-file: test/json_schema.json
